### ISSUE TITLE
Link to atlanis.net/blog out of date

### ISSUE THREAD

**Issue by emallson** [magnars/stasis#19]
[I updated my blog and no longer use stasis.](https://atlanis.net/blog/2015/09/08/new-blog-again/)

This isn't a problem with stasis/optimus, but ultimately with my hacky `org-mode` setup. I just got fed up with the whole thing and switched to a batteries-included SSG for my blog (since most SSGs address that problem well).

The github repo that is linked to is still accurate and (AFAIK) still works, but the blog link is no longer generated with stasis (though I'm not happy with my current setup and may end up going back to stasis soon).

**Comment by magnars** [comment]
Thanks for letting me know. I've fixed the README. Too bad that the org-mode thing didn't work out. It sounded really cool!

**Comment by emallson** [comment]
It was! but it was also high-maintenance, unfortunately. I had to fix something about it every time I went to write.
