### ISSUE TITLE
slurp-directory not working for me

### ISSUE THREAD

**Issue by kzar** [magnars/stasis#9]
slurp-directory seems to be attempting to slurp the root directory and therefore returning a FileNotFoundException. I guess the solution would be to filter away directories before slurping?
- I'm using 2.1.1
- My files are in `public/` directory inside my project. (Not in the resources directory.)
- `(file-seq (clojure.java.io/file "public/"))` works fine
- `(stasis.core/slurp-directory "public/" #".*")` returns "FileNotFoundException public  java.io.FileInputStream.open (FileInputStream.java:-2)"
- `(slurp (first (file-seq (clojure.java.io/file "public/"))))` also returns the same exception which could be a clue?

(Perhaps the exception is caused by something else, I'm not best person to say.)

Cheers, Dave.

**Comment by karneaud** [comment]
What if I want to map the directories to the root? e.g.

`slurp-directory "resourcses/md" .....`

> {"/", "....."}

How can I accomplish this with REGEX?

**Comment by magnars** [comment]
@karneaud I'm not sure I understand what you're trying to accomplish. Please expand you explanation in a new issue.

**Comment by karneaud** [comment]
@magnars 

its ok I was trying to build md files into the "/" of the build directory rather than "/dir/". I accomplished  this task by changing the regex. 

Works the way I want to now
